version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MASTODON_URL: https://social.griff.la
      MASTODON_TOKEN: 
      GPT_KEY: 
    ports:
      - 3000:3000
    networks:
      - app-net
networks:
  app-net:
